//Rock Paper Scissors - JavaScript

//Game will be playing against a computer - this is based off a function called computerPlay
//computerPlay will randomly return either 'Rock', 'Paper', 'Scissors'

/* Algorithm
    1. Computer generates RPS at random
    2. Console displays selection
    3. Player enters selection
    4. Console displays selection
    5. Compare - decide winner of the round
*/

//function which player chooses
function playerPick() {
    let playerChoice = prompt("Pick one of the following: Rock, Paper, Scissors");
    //return "Player chose: " + playerChoice;
    console.log("You picked: ", playerChoice);
    return playerChoice;
}

//function which computer choose a choice at random from an array
function computerPlay() {
    //Array of choices for computer to choose from
    let choices = ["Rock", "Paper", "Scissors"]; 
    let compChoice = choices[Math.floor(Math.random() * choices.length)];
    //return "Computer chose: " + compChoice;
    console.log("Computer picked: ", compChoice);
    return compChoice;
}

//function that plays a single round of RPS
function playRound(playerSelection, computerSelection) {
    //Player winning statements
    if (playerSelection == "Rock" && computerSelection == "Scissors") {
        return "Yay! You win!";
    } else if (playerSelection == "Scissors" && computerSelection == "Paper") {
        return "Yay! You win!";
    } else if (playerSelection == "Paper" && computerSelection == "Rock") {
        return "Yay! You win!";
    //Computer winning statements
    } else if (playerSelection == "Rock" && computerSelection == "Paper" || playerSelection == "Paper" && computerSelection == "Scissors" || playerSelection == "Scissors" && computerSelection == "Rock") {
        return "Dang! You lost!";
    //Draw statements
    } else (playerSelection === "Rock" && computerSelection === "Rock" || playerSelection === "Paper" && computerSelection === "Paper" || playerSelection === "Scissors" && computerSelection === "Scissors")
        return "Wow! Its a draw!";
}

//running the playRound function in console by using the variables picked by the player and generated by the computer
console.log(playRound(playerPick(), computerPlay()));





// IGNORE BELOW - Recorded mistakes, errors, brainstorming below

/* 1st iteration of if else loop - kept returning draw
function playRound(playerSelection, computerSelection) {
    if (playerSelection === "Rock" && computerSelection === "Scissors" || playerSelection === "Scissors" && computerSelection === "Paper" || playerSelection === "Paper" && computerSelection === "Rock") {
        return "Yay! You win!";
    } else if (playerSelection === "Rock" && computerSelection === "Paper" || playerSelection === "Paper" && computerSelection === "Scissors" || playerSelection === "Scissors" && computerSelection === "Rock") {
        return "Dang! You lost!";
    } else (playerSelection === "Rock" && computerSelection === "Rock" || playerSelection === "Paper" && computerSelection === "Paper" || playerSelection === "Scissors" && computerSelection === "Scissors")
        return "Wow! Its a draw!";
}
*/

/* 2nd iteration of if else loop - kept returning something went wrong... etc
function playRound(playerSelection, computerSelection) {
    //Rock choice
    if (playerSelection === "Rock" && computerSelection === "Scissors") {
        return "You win! Rock beats Scissors!";
    } else if (playerSelection === "Rock" && computerSelection === "Paper") {
        return "You lose! Paper beats Rock!";
    } else if (playerSelection === "Rock" && computerSelection === "Rock") {
        return "It's a draw! You both picked Rock!";
    //Paper choice
    } else if (playerSelection === "Paper" && computerSelection === "Rock") { 
        return "You win! Paper beats Rock!";
    } else if (playerSelection === "Paper" && computerSelection === "Scissors") {
        return "You lose! Scissors beats Paper!";
    } else if (playerSelection === "Paper" && computerSelection === "Paper") {
        return "It's a draw! You both picked Paper!";
    //Scissors choice
    } else if (playerSelection === "Scissors" && computerSelection === "Paper") {
        return "You win! Scissors beats Paper!";
    } else if (playerSelection === "Scissors" && computerSelection === "Rock") {
        return "You lose! Rock beats Scissors!";
    } else if (playerSelection === "Scissors" && computerSelection === "Scissors") {
        return "It's a draw! You both picked Scissors!";
    } else {
        return "Something went wrong. Did you enter the right item?";
    }
}
/*

/*
//Running the function for computer's random selection
computerPlay();

//Player enters a selection
function playerSelection() {
    let playerChoice = prompt("Pick one of the following: Rock, Paper, Scissors");
    console.log("Player chose: " + playerChoice);
}

//Running the function for player 
playerSelection();

//Comparing the scores of player and computer
*/

/*function playerSelection () {
    prompt("Pick one: Rock, Paper, or Scissors?");
}*/