//Rock Paper Scissors - JavaScript

//Game will be playing against a computer - this is based off a function called computerPlay
//computerPlay will randomly return either 'Rock', 'Paper', 'Scissors'

/* Algorithm
    1. Computer generates RPS at random
    2. Console displays selection
    3. Player enters selection
    4. Console displays selection
    5. Compare - decide winner of the round
*/

//function which prompts player to choose either rock, paper, or scissors.
function playerPick() {
    let playerChoice = prompt("Pick one of the following: Rock, Paper, Scissors");
    //return "Player chose: " + playerChoice;
    console.log("You picked: ", playerChoice);
    return playerChoice;
}

//function which computer choose a choice at random from an array.
function computerPlay() {
    //Array of choices for computer to choose from
    let choices = ["Rock", "Paper", "Scissors"]; 
    let compChoice = choices[Math.floor(Math.random() * choices.length)];
    //return "Computer chose: " + compChoice;
    console.log("Computer picked: ", compChoice);
    return compChoice;
}

//Variables that specify win/loss/draw messages
let playerWinRound = "You won this round!";
let computerWinRound = "You lost! Computer won this round!";
let noWinner = "No one wins! It was a draw!";
let playerFinalWinner = "YES! YOU WON THE GAME! CONGRATULATIONS!";
let computerFinalWinner = "SORRY! COMPUTER WINS THIS TIME! TRY AGAIN NEXT TIME!";

//Base scores
let playerScore = 0;
let computerScore = 0;

//Function to display player as winner and add score
function win() {
    playerScore++;
    console.log(playerWinRound);
    console.log("Total Player Points: " + playerScore);
}

//Function to display computer as winner and add score
function lose() {
    computerScore++;
    console.log(computerWinRound);
    console.log("Total Computer Points: " + computerScore);
}

//Function to display draw message
function draw() {
    console.log(noWinner);
}

//function that plays a single round of RPS.
function playRound(playerSelection, computerSelection) {
    //Player winning statements
    if ((playerSelection == "Rock" && computerSelection == "Scissors") || (playerSelection == "Scissors" && computerSelection == "Paper") || (playerSelection == "Paper" && computerSelection == "Rock")) {
        win();
    //Computer winning statements
    } else if ((playerSelection == "Rock" && computerSelection == "Paper") || (playerSelection == "Paper" && computerSelection == "Scissors") || (playerSelection == "Scissors" && computerSelection == "Rock")) {
        lose();
    //Draw statements
    } else {
        draw();
    }
}

//running the playRound function in console by using the inputs entered by the player and generated by the computer.
playRound(playerPick(), computerPlay());

//function to play a five round game that keeps score and reports a winner or loser at the end.
/*function game() {
    console.log(playRound(playerPick(), computerPlay()));
    console.log(playRound(playerPick(), computerPlay()));
    console.log(playRound(playerPick(), computerPlay()));
    console.log(playRound(playerPick(), computerPlay()));
    console.log(playRound(playerPick(), computerPlay()));
}
*/

//running the function to play the game five times
//game();

















// IGNORE BELOW - Recorded mistakes, errors, brainstorming below

/* 1st iteration of if else loop - kept returning draw
function playRound(playerSelection, computerSelection) {
    if (playerSelection === "Rock" && computerSelection === "Scissors" || playerSelection === "Scissors" && computerSelection === "Paper" || playerSelection === "Paper" && computerSelection === "Rock") {
        return "Yay! You win!";
    } else if (playerSelection === "Rock" && computerSelection === "Paper" || playerSelection === "Paper" && computerSelection === "Scissors" || playerSelection === "Scissors" && computerSelection === "Rock") {
        return "Dang! You lost!";
    } else (playerSelection === "Rock" && computerSelection === "Rock" || playerSelection === "Paper" && computerSelection === "Paper" || playerSelection === "Scissors" && computerSelection === "Scissors")
        return "Wow! Its a draw!";
}
*/

/* 2nd iteration of if else loop - kept returning something went wrong... etc
function playRound(playerSelection, computerSelection) {
    //Rock choice
    if (playerSelection === "Rock" && computerSelection === "Scissors") {
        return "You win! Rock beats Scissors!";
    } else if (playerSelection === "Rock" && computerSelection === "Paper") {
        return "You lose! Paper beats Rock!";
    } else if (playerSelection === "Rock" && computerSelection === "Rock") {
        return "It's a draw! You both picked Rock!";
    //Paper choice
    } else if (playerSelection === "Paper" && computerSelection === "Rock") { 
        return "You win! Paper beats Rock!";
    } else if (playerSelection === "Paper" && computerSelection === "Scissors") {
        return "You lose! Scissors beats Paper!";
    } else if (playerSelection === "Paper" && computerSelection === "Paper") {
        return "It's a draw! You both picked Paper!";
    //Scissors choice
    } else if (playerSelection === "Scissors" && computerSelection === "Paper") {
        return "You win! Scissors beats Paper!";
    } else if (playerSelection === "Scissors" && computerSelection === "Rock") {
        return "You lose! Rock beats Scissors!";
    } else if (playerSelection === "Scissors" && computerSelection === "Scissors") {
        return "It's a draw! You both picked Scissors!";
    } else {
        return "Something went wrong. Did you enter the right item?";
    }
}
/*

/*
//Running the function for computer's random selection
computerPlay();

//Player enters a selection
function playerSelection() {
    let playerChoice = prompt("Pick one of the following: Rock, Paper, Scissors");
    console.log("Player chose: " + playerChoice);
}

//Running the function for player 
playerSelection();

//Comparing the scores of player and computer
*/

/*function playerSelection () {
    prompt("Pick one: Rock, Paper, or Scissors?");
}*/